// Export pages
export '/admin/admin_main/admin_main_widget.dart' show AdminMainWidget;
export '/login/login/login_widget.dart' show LoginWidget;
export '/vendedor/vendedor_main/vendedor_main_widget.dart'
    show VendedorMainWidget;
export '/bodeguero/bodeguero_main/bodeguero_main_widget.dart'
    show BodegueroMainWidget;
export '/vendedor/vendedor_crear_factura/vendedor_crear_factura_widget.dart'
    show VendedorCrearFacturaWidget;
export '/admin/admin_crear_vendedor/admin_crear_vendedor_widget.dart'
    show AdminCrearVendedorWidget;
export '/admin/admin_crear_bodeguero/admin_crear_bodeguero_widget.dart'
    show AdminCrearBodegueroWidget;
export '/admin/admin_crear_ruta/admin_crear_ruta_widget.dart'
    show AdminCrearRutaWidget;
export '/admin/admin_crear_empresa_cliente/admin_crear_empresa_cliente_widget.dart'
    show AdminCrearEmpresaClienteWidget;
export '/vendedor/vendedor_menu_facturas/vendedor_menu_facturas_widget.dart'
    show VendedorMenuFacturasWidget;
export '/vendedor/vendedor_menu_camion/vendedor_menu_camion_widget.dart'
    show VendedorMenuCamionWidget;
export '/vendedor/vendedor_menu_ordenes/vendedor_menu_ordenes_widget.dart'
    show VendedorMenuOrdenesWidget;
export '/admin/admin_menu_bodeguero/admin_menu_bodeguero_widget.dart'
    show AdminMenuBodegueroWidget;
export '/admin/admin_menu_vendedor/admin_menu_vendedor_widget.dart'
    show AdminMenuVendedorWidget;
export '/admin/admin_menu_ruta/admin_menu_ruta_widget.dart'
    show AdminMenuRutaWidget;
export '/admin/admin_menu_empresa_cliente/admin_menu_empresa_cliente_widget.dart'
    show AdminMenuEmpresaClienteWidget;
export '/login/admin_page/admin_page_widget.dart' show AdminPageWidget;
export '/vendedor/vendedor_crear_orden/vendedor_crear_orden_widget.dart'
    show VendedorCrearOrdenWidget;
export '/vendedor/vendedor_crear_orden_copy/vendedor_crear_orden_copy_widget.dart'
    show VendedorCrearOrdenCopyWidget;
export '/mostrar/admin_buscar_cliente/admin_buscar_cliente_widget.dart'
    show AdminBuscarClienteWidget;
export '/mostrar/admin_buscar_vendedor/admin_buscar_vendedor_widget.dart'
    show AdminBuscarVendedorWidget;
export '/mostrar/admin_buscar_rutas/admin_buscar_rutas_widget.dart'
    show AdminBuscarRutasWidget;
export '/mostrar/admin_mostrar_bodeguero/admin_mostrar_bodeguero_widget.dart'
    show AdminMostrarBodegueroWidget;
export '/mostrar/vendedor_buscar_orden/vendedor_buscar_orden_widget.dart'
    show VendedorBuscarOrdenWidget;
export '/mostrar/vendedor_mostrar_factura/vendedor_mostrar_factura_widget.dart'
    show VendedorMostrarFacturaWidget;
export '/mostrar/mostrar_camion/mostrar_camion_widget.dart'
    show MostrarCamionWidget;
